config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 3 }
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  ARTICLES_PER_PAGE = 3
  def index
    @page = params.fetch(:page,0).to_i
    @articles = Article.offset(@page*ARTICLES_PER_PAGE).limit(ARTICLES_PER_PAGE)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
    end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control' %><br>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: 'form-control' %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <% end %>

app/views/articles/edit.html.erb
    <h4 >Edit Post</h4>
	
	
	<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Post</h1>
  <% @articles.each do |article| %>
          <p><%= link_to article.title, article %></p>
  <% end %>

<p><%= link_to "New Article", new_article_path %></p>

<div>
  <%= link_to 'Previous page', root_path(page: @page - 1) %>
  <%= link_to 'Next page', root_path(page: @page + 1) %>
</div>

app/views/articles/new.html.erb
<h1>New Post</h1>
	<h4 >Create new article</h4>
	<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

    <p><%= @article.body %></p>
    <ul>
      <p><%= link_to "Edit", edit_article_path(@article) %></p>
      <p><%= link_to "Delete", article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p>
    </ul>
	<h4>Add a comment:</h4>
		<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <%= comment.commenter %> :
  <%= comment.body %>
</p>

<ul>
  <%= link_to 'Delete', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</ul>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit%>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PVI KR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>